// @flow

// AI Scripts
export const AISCRIPT_LOADING = 'AI_SCRIPT_LOADING';
export const AISCRIPT_LOADING_ERROR = 'AISCRIPT_LOADING_ERROR';
export const AISCRIPT_LOADING_SUCCESS = 'AISCRIPT_LOADING_SUCCESS';
export const AISCRIPT_SET_FULL_PARSING = 'AISCRIPT_SET_FULL_PARSING';
export const AISCRIPT_SET_QUICK_PARSING = 'AISCRIPT_SET_QUICK_PARSING';

// App
export const APP_MENU_CONTRACT = 'APP_MENU_CONTRACT';
export const APP_ERROR = 'APP_ERROR';
export const APP_MENU_EXPAND = 'APP_MENU_EXPAND';
export const APP_LOADED = 'APP_LOADED';
export const APP_LOADER_REMOVED = 'APP_LOADER_REMOVED';
export const APP_LOADING = 'APP_LOADING';
export const APP_STORAGE_CREATED = 'APP_STORAGE_CREATED';

// Data
export const DATA_LOAD = 'DATA_LOAD';
export const DATA_LOAD_ERROR = 'DATA_LOAD_ERROR';
export const DATA_LOAD_SUCCESS = 'DATA_LOAD_SUCCESS';

// Eternity files
export const ETERNITY_LOAD = 'ETERNITY_LOAD';
export const ETERNITY_LOAD_SUCCESS = 'ETERNITY_LOAD_SUCCESS';
export const ETERNITY_LOAD_ERROR = 'ETERNITY_LOAD_ERROR';

// Forms
export const FORM_BUSY = 'FORM_BUSY';
export const FORM_ERROR = 'FORM_ERROR';
export const FORM_RESET = 'FORM_RESET';
export const FORM_SAVE = 'FORM_SAVE';
export const FORM_SUCCESS = 'FORM_SUCCESS';

// Languages
export const LANGUAGE_CHANGE = 'LANGUAGE_CHANGE';
export const LANGUAGE_LOAD = 'LANGUAGE_LOAD';
export const LANGUAGE_LOADED = 'LANGUAGE_LOADED';
export const LANGUAGE_LOAD_ERROR = 'LANGUAGES_LOAD_ERROR';
export const LANGUAGE_LOAD_SUCCESS = 'LANGUAGE_LOAD_SUCCESS';

// Settings
export const SETTINGS_LOAD = 'SETTINGS_LOAD';
export const SETTINGS_SAVE = 'SETTINGS_SAVE';
export const SETTINGS_SAVE_ERROR = 'SETTINGS_SAVE_ERROR';
export const SETTINGS_SAVE_SUCCESS = 'SETTINGS_SAVE_SUCCESS';
export const SETTINGS_LOAD_ERROR = 'SETTINGS_LOAD_ERROR';
export const SETTINGS_LOAD_SUCCESS = 'SETTINGS_LOAD_SUCCESS';

// Sidebar
export const SIDEBAR_LOADING = 'SIDEBAR_LOADING';
export const SIDEBAR_LOADING_ERROR = 'SIDEBAR_LOADING_ERROR';
export const SIDEBAR_LOADING_SUCCESS = 'SIDEBAR_LOADING_SUCCESS';
