/**
 * Action Type Constants
 */

// App
export const APP_ERROR = 'APP_ERROR';
export const APP_LOADED = 'APP_LOADED';
export const APP_LOADER_REMOVED = 'APP_LOADER_REMOVED';
export const APP_LOADING = 'APP_LOADING';
export const APP_STORAGE_CREATED = 'APP_STORAGE_CREATED';

// Data
export const DATA_LOAD = 'DATA_LOAD';
export const DATA_LOAD_ERROR = 'DATA_LOAD_ERROR';
export const DATA_LOAD_SUCCESS = 'DATA_LOAD_SUCCESS';

// Languages
export const LANGUAGE_LOAD = 'LANGUAGE_LOAD';
export const LANGUAGE_LOAD_ERROR = 'LANGUAGES_LOAD_ERROR';
export const LANGUAGE_LOAD_SUCCESS = 'LANGUAGE_LOAD_SUCCESS';

// Settings
export const SETTINGS_LOAD = 'SETTINGS_LOAD';
export const SETTINGS_UPDATE = 'SETTINGS_UPDATE';
export const SETTINGS_UPDATE_ERROR = 'SETTINGS_UPDATE_ERROR';
export const SETTINGS_UPDATE_SUCCESS = 'SETTINGS_UPDATE_SUCCESS';
export const SETTINGS_LOAD_ERROR = 'SETTINGS_LOAD_ERROR';
export const SETTINGS_LOAD_SUCCESS = 'SETTINGS_LOAD_SUCCESS';
